### ISSUE TITLE
Implement nodeagents for Framework

### ISSUE THREAD

**Issue by redtechtiger** [redtechtiger/swirve#23]
This would mean that all code regarding management of the Minecraft nodes will be done through a single daemon/process/thread, which would eliminate the need of so many threads. Furthermore, this nodeagent could do background work on the node, like clear pipe, analyse log, etc.

**Comment by RedTechTiger** [comment]
Similar approach will be taken in order to perform sanitary processes to all nodes, however already existing threads will not be refactored.
